### PR TITLE
Peng/95 lint md

### LINKED ISSUE #94: Test every URL to make sure it still works
We probably have a slew of broken URLs through our documents, either through typos or the churn of the internet.

- [x] test urls in the JSON and markdown content of `aib-data`
- [x] test every url in `tendermint.com`
- [x] test every url in `cosmos.network`

### LINKED ISSUE #95: Lint our markdown
Our markdown code has to be linted to make sure its valid, otherwise we could be breaking our websites by pushing to master.

- [x] grammar and spelling checker for markdown documents
- [x] validation checker for markdown documents

### PR DESCRIPTION
**Pull request by nylira**
Closes #95 
Closes #94 

- [x] adds markdown linter with recommended rules
- [x] adds a URL checker to the markdown linter
- [x] switches json linter to npm jsonlint
- [x] updates CircleCI config

This PR uses [remark-lint](https://github.com/remarkjs/remark-lint) for two new commands `yarn lint`, which lints our markdown files, and `yarn lint:fix`, which will fix all the errors that were brought up.

There are a lot of plugins we can add to `remark-lint` to improve our website content. For example, one can run all of our written content through `write-good`, an English prose linter. I want to turn it on right now, but I don't have the time right now to fix all of the errors they will bring up.

[List of extra Markdown linter rules](https://github.com/remarkjs/remark-lint#list-of-external-rules)

Right now CircleCI will generate warnings for broken links. What is the best solution for dealing with broken links?

### CODE REVIEW

**Comment by zramsay** [comment]
sweet. 

> What is the best solution for dealing with broken links?

fix if easy to do so or remove

**Comment by zramsay** [comment]
where is `npm jsonlint` being run. i don't see it in the circleCI config file

**Comment by nylira** [comment]
It's included in `package.json`'s `yarn lint` command, which does the md and json lint.

https://github.com/tendermint/aib-data/pull/175/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R16

**Comment by zramsay** [comment]
oh gotcha, awesome

**Comment by nylira** [comment]
I've replaced `jsonlint-cli` and `remark`'s weird defaults in favor of `Prettier`. Now we just use `remark` to check for dead urls, and `textlint` to check for banned phrases.

**Pull request merged**
