### PR TITLE
peng/write-good

### PR DESCRIPTION
**Pull request by nylira**
- [x] enable lint warnings using write-good

Write Good is a linter for English that warns you about word repetitions, weasel words, adverbs, wordiness, and cliches. I think we should use a linter to improve our writing, and this is a decent choice.

This addition does give us a lot of warnings to fix, but I think that's good thing. It means that we can write better.

### CODE REVIEW

**Comment by nylira** [comment]
Example warnings:

screen shot 2018-07-04 at 16 01 34

**Comment by jolesbi** [comment]
we should probably fix the warnings before we merge this. i would be happy to help.

**Comment by nylira** [comment]
Yes, please do so! @jolesbi

**Comment by jolesbi** [comment]
is this relevant now that we're moving the content elsewhere?

**Comment by nylira** [comment]
I will implement this separately per-website repo. This PR is deprecated.

**Pull request closed without merging**
